build-project-v01:
  stage: build
  script: /root/build
  only:
    - /^v.*$/
  tags:
    - dreamcast-hdmi-v0.1

build-project:
  stage: build
  script: /root/build
  except:
    - /^v.*$/
  tags:
    - dreamcast-hdmi

publish-project:
  stage: deploy
  script: create-index-html
  tags:
    - index-gen
