
firmware:
  stage: build
  script: /root/build
  artifacts:
    paths:
    - output_files/*.jic
    - output_files/*.rbf
  tags:
    - dreamcast-hdmi

publish:
  stage: deploy
  script: create-index-html
  dependencies: []
  tags:
    - index-gen
