
firmware:
  stage: build
  script: /root/build
  artifacts:
    paths:
    - Core/output_files/*.jic
    - Core/output_files/*.rbf
    - Core/output_files/*.dc
  tags:
    - dreamcast-hdmi

publish:
  stage: deploy
  script: create-index-html
  artifacts:
    expire_in: 1 sec
  tags:
    - index-gen
